# This is a basic workflow to help you get started with Actions

name: Pre-Merge Actions

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'zulu'
    - name: Grant execute permission for scripts
      run: chmod +x gradlew

    # Set environment variables
    - name: Export Properties
      id: properties
      shell: bash
      run: |
        PROPERTIES="$(./gradlew properties --console=plain -q)"
        VERSION="$(echo "$PROPERTIES" | grep "^version:" | cut -f2- -d ' ')"
        
        echo "::set-output name=version::$VERSION"
        echo "::set-output name=pluginVerifierHomeDir::~/.pluginVerifier"
        
        ./gradlew listProductsReleases # prepare list of IDEs for Plugin Verifier


    - name: Perform quality check
      run: ./gradlew clean check

      # Cache Plugin Verifier IDEs
    - name: Setup Plugin Verifier IDEs Cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.properties.outputs.pluginVerifierHomeDir }}/ides
        key: plugin-verifier-${{ hashFiles('build/listProductsReleases.txt') }}

      # Run Verify Plugin task and IntelliJ Plugin Verifier tool
    - name: Run Plugin Verification tasks
      run: ./gradlew runPluginVerifier -Pplugin.verifier.home.dir=${{ steps.properties.outputs.pluginVerifierHomeDir }}

      # Collect Plugin Verifier Result
    - name: Collect Plugin Verifier Result
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: pluginVerifier-result
        path: ${{ github.workspace }}/build/reports/pluginVerifier

