# This is a basic workflow to help you get started with Actions

name: Pre-Merge Actions

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'zulu'
    - name: Grant execute permission for scripts
      run: chmod +x gradlew
    - name: Perform quality check
      run: ./gradlew clean check buildPlugin
    - uses: ChrisCarini/intellij-platform-plugin-verifier-action@v1.2.1
      with:
        ide-versions: |
          ideaIC:2020.3.1
          ideaIU:2020.3.1
          ideaIC:LATEST-EAP-SNAPSHOT
          ideaIU:LATEST-EAP-SNAPSHOT
